<a href="https://colab.research.google.com/github/raghulchandramouli/breaking-into-Computational-Graphs-/blob/main/Automatic_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AutoGrad
> Automatic differentiation (AD) is a set of techniques used to evaluate the partial derivative of a function specified by a computer program. It allows for efficient and accurate calculation of derivatives of numeric functions expressed as computer programs.



In [7]:
# If requires_grad = True, the tensor object keeps track of how it was created
import torch

x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)

# Notice that both of x and y have their required_grad to true, therefore we an comoute gradients with respect to them
z = x + y
print(z)

# z knows that it was created as a result of addition of x and y, It knows that it wasn't read in from a file
print(z.grad_fn)
# And if we fo further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [8]:
# Now if we backpropagate on s, we can find the gradients of s with respect to x:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [ ]:
# By default, Tensors have `requires_grad = False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y

# So you can't backprop through z
print(z.grad_fn)

# Another way to set the required_grad is true:
x.requires_grad_()
y.requires_grad_()

# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)

# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)

# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?

new_z = z.detach()
print(new_z.grad_fn)
# ... does new_z have information to backprop to x and y?
# NO!

print(x.requires_grad)
print((x + 10).requires_grad)

with torch.no_grad():
    print((x + 10).requires_grad)

In [12]:
# last example:
x = torch.ones(2,2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
