<a href="https://colab.research.google.com/github/raghulchandramouli/breaking-into-Computational-Graphs-/blob/main/Loss_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loss Functions:

A `loss function` is a crucial component in machine learning that quantifies the difference between the predicted outputs of a model and the actual target values. It serves as a guide for the learning process, helping to adjust the model's parameters to minimize errors and improve performance.

**Key Principles**

*   `Performance Benefits :` Loss functions provide a clear metric to evaluate a model's performance by quantifying the difference between predictions and actual results.
*   `Direction for improvement :` They guide model improvement by directing the algorithm to adjust parameters iteratively to reduce loss and improve predictions.
*   `Balancing Bias and Variance :` Effective loss functions help balance model bias (oversimplification) and variance (overfitting), essential for the model's generalization to new data.



In [6]:
import torch
import torch.nn as nn

In [12]:
prediction = torch.randn(4, 5) # Subjective to

tensor([[-0.7151, -0.5270, -1.1826,  2.3416, -0.2517],
        [ 0.3528, -0.5343,  1.2426, -1.5218, -0.6690],
        [-0.0890, -0.1483,  2.0760,  0.8813,  0.0722],
        [-0.7792, -0.8716, -0.1874,  0.9095, -1.1980]])

In [4]:
label = torch.randn(4, 5)

In [27]:
mse = nn.MSELoss(reduction='mean')

In [28]:
loss = mse(prediction, label)

In [29]:
loss

tensor(3.4064)

In [30]:
(prediction - label).pow(2).mean()

tensor(3.4064)

In [31]:
prediction

tensor([[-0.7151, -0.5270, -1.1826,  2.3416, -0.2517],
        [ 0.3528, -0.5343,  1.2426, -1.5218, -0.6690],
        [-0.0890, -0.1483,  2.0760,  0.8813,  0.0722],
        [-0.7792, -0.8716, -0.1874,  0.9095, -1.1980]])

In [38]:
label = torch.zeros(4, 5).random_(0, 2)
label

tensor([[1., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0.],
        [1., 0., 0., 1., 1.],
        [1., 0., 1., 1., 0.]])

In [39]:
sigmoid = nn.Sigmoid()

In [41]:
bce = nn.BCELoss(reduction='mean')

In [42]:
bce(sigmoid(prediction), label)

tensor(0.8003)

In [46]:
# with logits loss:
bces = bce = nn.BCEWithLogitsLoss(reduction='mean')

In [48]:
bce(prediction, label)

tensor(0.8003)

In [49]:
import numpy as np

x = prediction.numpy()
y = label.numpy()

In [52]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [54]:
x = sigmoid(x)

loss_values = []
for i in range(len(y)):
  batch_loss = []
  for j in range(len(y[0])):
      # Using numpy functions directly for binary cross-entropy calculation
      batch_loss.append(-(x[i][j] if y[i][j] == 1 else -np.log(1 - x[i][j])))
  loss_values.append(batch_loss)

print(np.mean(loss_values))

-0.6205319313659122
